apiVersion: v1
kind: Service
metadata:
  name: headless-svc
spec:
  clusterIP: None
  selector:
    job-name: tpu-available-chips
---
apiVersion: batch/v1
kind: Job
metadata:
  name: tpu-available-chips
spec:
  backoffLimit: 0
  completions: 4
  parallelism: 4
  completionMode: Indexed
  template:
    spec:
      subdomain: headless-svc
      restartPolicy: Never
      nodeSelector:
                cloud.google.com/gke-tpu-accelerator: tpu-v6e-slice
                cloud.google.com/gke-tpu-topology: 4x4
      volumes:
            - name: output
              emptyDir: {}
              #- name: gcs-fuse-csi-ephemeral
              #  csi:
              #     driver: gcsfuse.csi.storage.gke.io
              #     readOnly: false
              #     volumeAttributes:
              #       bucketName: mdonati-h200-uscentral1
              #       mountOptions: "implicit-dirs"
              #       fileCacheCapacity: "-1Mi"
              #       fileCacheForRangeRead: "true"
              #       metadataCacheTTLSeconds: "-1"
              #       metadataNegativeCacheTTLSeconds: "0"
              #       metadataStatCacheCapacity: "-1Mi"
              #       metadataTypeCacheCapacity: "-1Mi"     
              
      containers:
              - name: maxtext
                image: us-east4-docker.pkg.dev/diesel-patrol-382622/gke-llm/maxtext_base_image:latest
                imagePullPolicy: Always
                ports:
                - containerPort: 8471
                - containerPort: 8080 # Port for MXLA coordinator
                securityContext:
                  privileged: true
                env:
                - name: JOBSET_NAME
                  value: "maxtext-vlp16-default"
                - name: LIBTPU_INIT_ARGS
                  value: "--xla_enable_async_all_gather=true TPU_MEGACORE=MEGACORE_DENSE"
                - name: TPU_STDERR_LOG_LEVEL
                  value: "0"
                - name: TPU_MIN_LOG_LEVEL
                  value: "0"
                - name: TF_CPP_MIN_LOG_LEVEL
                  value: "0"
                command:
                - bash
                - -c
                - |
                   python3 -m benchmarks.benchmark_runner on-device \
                   --base_output_directory="/output/tpu-benchmark" \
                   --model_name="llama3_1_8b_8192_no_collective_matmul" \
                   --run_name="test-run" \
                   --num_steps 50
                   
                resources:
                  limits:
                    google.com/tpu: 4
                volumeMounts:
                - name: output
                  mountPath: /output
                #- name: gcs-fuse-csi-ephemeral
                #  mountPath: /gcs-dir


